### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by bguernouti** [Pelectrome/Dz_Inventors_Live_Chat#3]
The root project is missing the **Environment** packages dependencies file, the basic one is the **requirements.txt** can be generated using **pip** `pip freeze > requirements.txt`.

The requirements.txt file is important, it allows the user to run the project locally with the same packages used in the production version of the code, so any pull request or any change suggested by any user will have a 100% chance to work on the production environment, because of the synchronized packages.

**Comment by Pelectrome** [comment]
thank you so much, requirements is added.
